CREATE TABLE `p_order` (
                           `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT 'ID',
                           `serial_no` varchar(32) NOT NULL COMMENT '订单号',
                           `predict_sum` decimal(14,5) NOT NULL COMMENT '订单金额（单位：元）',
                           `discounts_sum` decimal(14,5) DEFAULT NULL COMMENT '优惠金额（单位：元）',
                           `logistics_sum` decimal(14,5) DEFAULT NULL COMMENT '运费金额（单位：元）',
                           `actual_sum` decimal(14,5) DEFAULT NULL COMMENT '实付金额（单位：元）',
                           `pay_method_id` bigint(20) DEFAULT NULL COMMENT '关联支付方式表',
                           `logistics_id` bigint(20) DEFAULT NULL COMMENT '关联物流表',
                           `order_state` int(2) NOT NULL COMMENT '订单状态（）',
                           `logistics_state` int(2) NOT NULL COMMENT '物流状态（）',
                           `operator_id` bigint(20) NOT NULL COMMENT '下单用户ID（关联user表ID）',
                           `remark` varchar(255) DEFAULT NULL COMMENT '订单备注',
                           `operation_id` bigint(20) NOT NULL COMMENT '上传人ID',
                           `create_time` datetime NOT NULL COMMENT '创建时间',
                           `change_time` datetime NOT NULL COMMENT '更新时间',
                           `logistics_time` datetime DEFAULT NULL COMMENT '发货时间',
                           `success_time` datetime DEFAULT NULL COMMENT '完成时间',
                           `sign` int(2) NOT NULL COMMENT '逻辑删除标识（1：正常；2：删除）',
                           PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=1000003 DEFAULT CHARSET=utf8mb4 COMMENT='订单表';